Repository evilsoft/crocks, pull requests merged in 2019-07, with the labels that each got.

#413 Suggestion for update on index exports
  src/pointfree/index.spec.js
Labels: WIP

#430 Changing toPairs to return an array
  docs/src/pages/docs/crocks/Pair.md
  docs/src/pages/docs/functions/helpers.md
  docs/src/pages/docs/functions/index.md
  src/Pair/toPairs.js
  src/Pair/toPairs.spec.js
Labels: breaking

#437 Clear up Security :corn:cerns
  package-lock.json
  package.json
Labels: chore

#433 Require Monoid Instance for Log Entry When Constructing A Writer
  src/Pair/writerToPair.spec.js
  src/Writer/Writer.spec.js
  src/Writer/index.js
Labels: breaking
